### ISSUE TITLE
Need guidance for what to do when receiving a setup message for an account that we already have a secret key for

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#277] opened 2017-12-12 19:25 UTC
Some MUA will have a secret key for account `A` already, and then they'll see an Autocrypt Setup Message for `A` that contains a different key.

What should the MUA do in that situation?  we need clear guidance so that we don't have wildly different behaviors.

**Comment by dkg** [comment] 2017-12-14 22:24
We currently only recommend looking for ASMs when enabling Autocrypt on an account for the first time.

Some options:

 a) completely ignore ASMs for an account if you already have a key for it.  If the user disables and then re-enables Autocrypt, just keep the old key.

 b) if the user disables and then re-enables, do the scan at that point, and offer them a choice between the old key and the discovered key (or discovered keys, in the event that more than one was found?)

 c) when disabling Autocrypt, offer the user an opportunity to destroy their key, and access to all of the e-mail that might have been encrypted to it.  this completely resets their state, which would allow them to scan for a new key at that point.

 d) do not require the user to disable/enable Autocrypt to scan for keys -- instead, next to enable/disable, offer a choice like "look for a setup message from other Autocrypt e-mail programs"

 e) during regular mail scanning, if an ASM is encountered for an account that is already locally autocrypt-enabled, actively offer the user a choice between the setup in the new ASM, and the existing setup.


Any other suggestions?  does anyone have any strong feelings about what the Right Thing™ is?  what about the Right Thing™ for Level 1?  (a) is certainly the easiest to do, but maybe the most frustrating for users, who will need to set up an entirely new MUA profile if they've gotten into that state.  Might be ok for L1, though.

(c) is appealing to me for L1 because:

 * it's simple to implement
 * the "delete my state" feature seems like it might be useful anyway, for privacy reasons.  Being able to confidently delete sensitive material is a good thing.
 * it doesn't require too much extra UI, or complicated questions.

**Comment by r10s** [comment] 2017-12-15 11:58
I would got for e) as the Right Thing™ - if there is a "fresh incoming ASM", show it to the user and ask if he wants to import the key and warn if there is already an existing one. Disabling Autocrypt should not delete existing keys.

Reasons: 

- normally, the user has initiated the process on another device, I think, this is a strong clue the user wants to use the key.
- easy to implement - in fact, I think this is already the current state for Enigmail and Delta - every ASM is shown as a - more or less - normal incoming message with a "start setup" button - it's up to the user to click or not to click.  
- few additional UI elements (a single question)
- a "disable Autocrypt" followed by an "enable Autocryot" does not result in unreadable mail as no keys are deleted on disabling Autocrypt.

Maybe the old key can be used as a legacy key, at least for a while. 

c) is an interesting option to get rid of all evidence on a device, however, if we "offer the option to delete the keys" and the user say "no", we fallback to the other options.

**Comment by dkg** [comment] 2017-12-15 21:54
So, if (e) is The Right Thing™, is it also the L1 thing?  or is it something for a future level?

I'm not so convinced that it's easy to implement.  we're talking about a whole new chunk of UI that the current spec doesn't contemplate at all.  Also, viewing the message is one thing, but receiving the message is another -- should the proposed new UI show up when the MUA first encounters the message?  or should it show up only when the MUA first foregrounds the message to the user?

When dealing with this new UI, does the user understand that clicking "start setup" means "destroy the existing key and remove my ability to access all mails that were encrypted to it"?  how can we be sure?

To clarify what i mean for (c), i meant that the act of disabling would show the user the ability to destroy the old key, but it wouldn't require it.  So for a given account, Autocrypt could basically be:

 * enabled with a key
 * disabled, with an old key still stored
 * disabled, with no key at all.

Conveniently, i think the internal state we've got documented already covers these possibilities.

If you prefer (e) though, would you be up for trying to propose a patch for the spec that describes what to do?

**Comment by r10s** [comment] 2017-12-16 01:03
I've just create a pull request.

I think the warning that must be confirmed by the user would be similar to the one that must be shown when asking the user whether to destroy his key by a Autocrypt-disable.

If the user really understands what he is doing - either on Import-Overwrite-Key or on Disable-Destroy-Key - well, I don't know :)

That the user may also loose access to existing messages - thank you for mentioning it again - because of too much Delta I had this out of focus.

Maybe a better way would be to keep the previous keys as a legacy key, however, this would also require to transfer the keys in the next ASM ...

**Comment by dkg** [comment] 2017-12-18 23:46
I've just proposed (c) as PR #287 -- it took more text than i was expecting, but i think that text was actually missing from the draft anyway, since the draft doesn't really cover the tail end of the Autocrypt lifecycle (we don't want to imagine people turning off encryption, but we should still specify the user experience there!).

I think that merging #287 would on its own satisfy me that this issue is resolved for L1, though i agree with r10s that there are more robustly correct approaches that can be taken for more sophisticated clients willing to store a history of secret keys.

But the more i think about it, the more i think those robust approaches should wait to level 2, so we can get Level 1 finalized as a baseline.

**Comment by dkg** [comment] 2017-12-20 18:28
#287 got simplified in a way that it no longer addressed this particular concern.  I've opened #294 in an attempt to clear the L1 milestone on this issue.

**Comment by hpk42** [comment] 2017-12-21 08:22
With #294 merged we can close this issue. Thanks @dkg for caring for this intricate issue (that will continue to busy us, i am sure).

**Comment by dkg** [comment] 2017-12-21 19:21
I don't think we should close this issue, i think we should just remove the Level 1 milestone marker, since we have a "level 1" fix, but not a general fix.

**Closed** 2024-06-10 10:36 UTC
Labels: setup message, UX
